name: education_app_tutorial
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.0.0
  chewie: ^1.10.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  file_picker: ^8.3.5
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.0.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.0+3
  swipe_to: ^1.0.6
  url_launcher: ^6.3.1
  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4


flutter:
  uses-material-design: true